## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - 1.5
  - nightly

notifications:
  email: false

matrix:
 allow_failures:
   - julia: nightly

after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("Geodesics")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
